//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecuacion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ecuacion
    {
        public Ecuacion()
        {
            this.EvaluacionEcuacions = new HashSet<EvaluacionEcuacion>();
        }
    
        public int ecuacion_id { get; set; }
        public Nullable<decimal> ecuacion_a { get; set; }
        public Nullable<decimal> ecuacion_b { get; set; }
        public Nullable<decimal> ecuacion_c { get; set; }
    
        public virtual ICollection<EvaluacionEcuacion> EvaluacionEcuacions { get; set; }
    }
}
